DROP TABLE IF EXISTS ACCOUNT;

CREATE TABLE ACCOUNT(id BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL, userId BIGINT NOT NULL, amount DECIMAL(65,2) NOT NULL);

INSERT INTO ACCOUNT(userId, amount) VALUES (1, 100.00);
INSERT INTO ACCOUNT(userId, amount) VALUES (2, 200.00);
INSERT INTO ACCOUNT(userId, amount) VALUES (3, 200.00);